Check that all API parameters use camel case
infrahq/infra pull request #3770
Opened 2022-11-30 20:31 UTC by dnephin

## Summary

This PR adds some validation to our OpenAPI document generation to catch when we use the wrong form of a parameter name. All our of parameters should use `camelCase` for consistently.

The document generation always runs in CI, so we'll catch this panic as a test failure in dev before merging any PRs.

I added a temporary allow list for the two fields that don't conform to the convention, which we'll remove once they are fixed.

I believe the parameter name always comes from `getFieldName`, so it should be safe to validate it here for now.

Related to #3590, and #3768

2022-11-30 20:32 UTC, dnephin commented on internal/server/openapi.go
> +	case "created_by", "unique_id":
`created_by` is fixed by #3768

I think we'll be able to remove `uniqueID` soon, so it's probably not worth renaming that one. Let's remove it sometime in the next release or two.

2022-11-30 20:36 UTC, jmorganca approved these changes

2022-11-30 20:38 UTC, ssoroka requested changes
Form fields are supposed to be underscore, aren't they? Hmm. Nevermind, I guess I'm mistaken.
We should probably validate the `header` fields are valid header tags with underscores.

2022-11-30 21:44 UTC, dnephin commented
> We should probably validate the header fields are valid header tags with underscores.

Right now the only headers we include in the document are hardcoded into `buildRequest` in `openapi.go`. We pass them directly to a method in a third-party library, so there's not really any place for us to do that validation.

Maybe in the future we could write something that reads the openAPI document and validates the document?

The change in this PR should catch all of the bugs we've encountered so far, so I think it's worth it to make this change now and do additional validation later.

2022-12-05 17:03 UTC, ssoroka approved these changes

2022-12-05 17:07 UTC, dnephin commented on internal/server/openapi.go
> +	case "created_by", "unique_id":
I removed `created_by` from this list, since #3768 has merged.

2022-12-05 17:25 UTC, merged